import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SimpleChart from '../charts/SimpleChart';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Airport weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plane.png" />
      </Head>

      <SimpleChart />
    </div>
  );
}
